force-app/main/default/objects/Film__c/Film__c.object-meta.xml
<CustomObject>
    <label>Film</label>
    <nameField>
        <label>Film Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Films</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Film__c/fields/Audio__c.field-meta.xml
<CustomField>
    <fullName>Audio__c</fullName>
    <label>Audio</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Film__c/fields/Cast__c.field-meta.xml
<CustomField>
    <fullName>Cast__c</fullName>
    <label>Cast</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Film__c/fields/Director__c.field-meta.xml
<CustomField>
    <fullName>Director__c</fullName>
    <label>Director</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Film__c/fields/FormatOfVideo__c.field-meta.xml
<CustomField>
    <fullName>FormatOfVideo__c</fullName>
    <label>FormatOfVideo</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Film__c/fields/Genre__c.field-meta.xml
<CustomField>
    <fullName>Genre__c</fullName>
    <label>Genre</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Film__c/fields/LengthOfFilm__c.field-meta.xml
<CustomField>
    <fullName>LengthOfFilm__c</fullName>
    <label>LengthOfFilm</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Film__c/fields/OriginalAudio__c.field-meta.xml
<CustomField>
    <fullName>OriginalAudio__c</fullName>
    <label>OriginalAudio</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Film__c/fields/PosterUrl__c.field-meta.xml
<CustomField>
    <fullName>PosterUrl__c</fullName>
    <label>PosterUrl</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Film__c/fields/QualityOfVideo__c.field-meta.xml
<CustomField>
    <fullName>QualityOfVideo__c</fullName>
    <label>QualityOfVideo</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Film__c/fields/Subtitles__c.field-meta.xml
<CustomField>
    <fullName>Subtitles__c</fullName>
    <label>Subtitles</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Film__c/fields/Translation__c.field-meta.xml
<CustomField>
    <fullName>Translation__c</fullName>
    <label>Translation</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Film__c/fields/Video__c.field-meta.xml
<CustomField>
    <fullName>Video__c</fullName>
    <label>Video</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Film__c/fields/YearOfProduction__c.field-meta.xml
<CustomField>
    <fullName>YearOfProduction__c</fullName>
    <label>YearOfProduction</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/StorageController.cls
public without sharing class StorageController {
    private static final List<String> columnData = new List<String>{
        'Name',
        'Country__c',
        'Genre__c',
        'Director__c',
        'Cast__c',
        'YearOfProduction__c',
        'LengthOfFilm__c'
    };

    private static final List<String> fieldsForQuery = new List<String>{
        'Id',
        'Name',
        'Country__c',
        'Genre__c',
        'YearOfProduction__c',
        'Translation__c',
        'FormatOfVideo__c',
        'QualityOfVideo__c',
        'Description__c',
        'Cast__c',
        'Director__c',
        'OriginalAudio__c',
        'Subtitles__c',
        'Video__c',
        'Audio__c',
        'PosterUrl__c',
        'LengthOfFilm__c'
    };

    @AuraEnabled
    public static Response getContacts(ParamsWrapper params){
        SoqlService soql = new SoqlService('Film__c');
        soql.setFields(fieldsForQuery);
        soql.setLimit(params.pageSize);
        soql.setOffset(params.pageSize * params.currentPage);

        Response resp = new Response();
        resp.amountOfRecords = soql.getAmountOfRecords();
        resp.columnData = columnData;
        resp.cellsData = (List<Film__c>)soql.doSoql();

        return resp;
    }

    public class ParamsWrapper {
        @AuraEnabled public Integer pageSize { get; set; }
        @AuraEnabled public Integer currentPage { get; set; }
    }

    public class Response {
        @AuraEnabled public Integer amountOfRecords { get; set; }
        @AuraEnabled public List<Film__c> cellsData { get; set; }
        @AuraEnabled public List<String> columnData { get; set; }
    }
}